# Generated by Django 6.0.8 on 2026-08-16 23:48

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrower', models.CharField(max_length=200)),
                ('principal', models.DecimalField(decimal_places=2, max_digits=18)),
                ('annual_rate', models.DecimalField(decimal_places=4, max_digits=6)),
                ('fees', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('limit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('opened_on', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Hold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('settled', 'Settled'), ('released', 'Released')], default='pending', max_length=16)),
                ('placed_on', models.DateField()),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holds', to='bank.loan')),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('cash', 'Cash'), ('principal_receivable', 'Principal receivable'), ('interest_receivable', 'Interest receivable'), ('fees_receivable', 'Fees receivable')], max_length=32)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('loan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='bank.loan')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memo', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('effective_on', models.DateField()),
                ('loan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='bank.loan')),
            ],
        ),
        migrations.CreateModel(
            name='Posting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='postings', to='bank.account')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postings', to='bank.transaction')),
            ],
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(fields=('kind', 'loan'), name='one_account_per_kind_per_loan'),
        ),
        migrations.AddConstraint(
            model_name='posting',
            constraint=models.UniqueConstraint(fields=('transaction', 'account'), name='one_posting_per_account_per_txn'),
        ),
    ]
